/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guipegawai;

/**
 *
 * @author insan
 */
public class menupegawai extends javax.swing.JFrame {

    /**
     * Creates new form menupegawai
     */
    public menupegawai() {
        initComponents();
        this.setSize(1278, 730);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lihatdata = new javax.swing.JButton();
        kelolacuti = new javax.swing.JButton();
        lihatgaji = new javax.swing.JButton();
        chekinabsen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAJEMENT KEPEGAWAIAN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RUMAH SAKIT");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 110));

        lihatdata.setBackground(new java.awt.Color(204, 255, 204));
        lihatdata.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lihatdata.setForeground(new java.awt.Color(0, 102, 51));
        lihatdata.setText("Lihat Data Pegawai");
        getContentPane().add(lihatdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 187, 46));

        kelolacuti.setBackground(new java.awt.Color(204, 255, 204));
        kelolacuti.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        kelolacuti.setForeground(new java.awt.Color(0, 102, 51));
        kelolacuti.setText("Kelola Cuti");
        kelolacuti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelolacutiActionPerformed(evt);
            }
        });
        getContentPane().add(kelolacuti, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 187, 46));

        lihatgaji.setBackground(new java.awt.Color(204, 255, 204));
        lihatgaji.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lihatgaji.setForeground(new java.awt.Color(0, 102, 51));
        lihatgaji.setText("Lihat Gaji");
        lihatgaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatgajiActionPerformed(evt);
            }
        });
        getContentPane().add(lihatgaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 540, 187, 46));

        chekinabsen.setBackground(new java.awt.Color(204, 255, 204));
        chekinabsen.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        chekinabsen.setForeground(new java.awt.Color(0, 102, 51));
        chekinabsen.setText("Chek-In Absen");
        chekinabsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekinabsenActionPerformed(evt);
            }
        });
        getContentPane().add(chekinabsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 187, 46));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lihatgaji.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 410, 310));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lihatdata.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 410, 310));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelolacuti.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 410, 310));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chekinabsen.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 410, 310));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Selamat Datang");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backround.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1280, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kelolacutiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelolacutiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelolacutiActionPerformed

    private void lihatgajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatgajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lihatgajiActionPerformed

    private void chekinabsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekinabsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chekinabsenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menupegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menupegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menupegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menupegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menupegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chekinabsen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kelolacuti;
    private javax.swing.JButton lihatdata;
    private javax.swing.JButton lihatgaji;
    // End of variables declaration//GEN-END:variables
}
