/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiadmin;

/**
 *
 * @author insan
 */
public class keloladatapegawai extends javax.swing.JFrame {

    /**
     * Creates new form keloladatapegawai
     */
    public keloladatapegawai() {
        initComponents();
        this.setSize(1278, 730);
        this.setResizable(false);
        this.setLocationRelativeTo(null);;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tambahdata = new javax.swing.JButton();
        updatedata = new javax.swing.JButton();
        hapusdata = new javax.swing.JButton();
        kelolagaji = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAJEMENT KEPEGAWAIAN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RUMAH SAKIT");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelolagaji.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(952, 265, 286, 286);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tambah data.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 265, 286, 286);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update data.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(344, 265, 286, 286);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hapus data.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(648, 265, 286, 286);

        tambahdata.setBackground(new java.awt.Color(204, 255, 204));
        tambahdata.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tambahdata.setForeground(new java.awt.Color(0, 102, 51));
        tambahdata.setText("Tambah Data");
        tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahdataActionPerformed(evt);
            }
        });
        getContentPane().add(tambahdata);
        tambahdata.setBounds(40, 569, 286, 46);

        updatedata.setBackground(new java.awt.Color(204, 255, 204));
        updatedata.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updatedata.setForeground(new java.awt.Color(0, 102, 51));
        updatedata.setText("Update Data");
        updatedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedataActionPerformed(evt);
            }
        });
        getContentPane().add(updatedata);
        updatedata.setBounds(344, 569, 286, 46);

        hapusdata.setBackground(new java.awt.Color(204, 255, 204));
        hapusdata.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        hapusdata.setForeground(new java.awt.Color(0, 102, 51));
        hapusdata.setText("Hapus Data");
        hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusdataActionPerformed(evt);
            }
        });
        getContentPane().add(hapusdata);
        hapusdata.setBounds(648, 569, 286, 46);

        kelolagaji.setBackground(new java.awt.Color(204, 255, 204));
        kelolagaji.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        kelolagaji.setForeground(new java.awt.Color(0, 102, 51));
        kelolagaji.setText("Kelola Gaji");
        kelolagaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelolagajiActionPerformed(evt);
            }
        });
        getContentPane().add(kelolagaji);
        kelolagaji.setBounds(952, 569, 286, 46);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backround.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 20, 1278, 703);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahdataActionPerformed

    private void updatedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatedataActionPerformed

    private void hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusdataActionPerformed

    private void kelolagajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelolagajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelolagajiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(keloladatapegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(keloladatapegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(keloladatapegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(keloladatapegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new keloladatapegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapusdata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kelolagaji;
    private javax.swing.JButton tambahdata;
    private javax.swing.JButton updatedata;
    // End of variables declaration//GEN-END:variables
}
