/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiadmin;

/**
 *
 * @author insan
 */
public class kelolajadwalkerja extends javax.swing.JFrame {

    /**
     * Creates new form kelolajadwalkerja
     */
    public kelolajadwalkerja() {
        initComponents();
        this.setSize(1278, 730);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hapusjadwal = new javax.swing.JButton();
        updatejadwal = new javax.swing.JButton();
        tambahjadwal = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAJEMENT KEPEGAWAIAN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RUMAH SAKIT");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 110);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tambah data.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(113, 215, 286, 286);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update data.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(492, 215, 286, 286);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hapus data.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(878, 215, 286, 286);

        hapusjadwal.setBackground(new java.awt.Color(204, 255, 204));
        hapusjadwal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        hapusjadwal.setForeground(new java.awt.Color(0, 102, 51));
        hapusjadwal.setText("Hapus Absen");
        hapusjadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusjadwalActionPerformed(evt);
            }
        });
        getContentPane().add(hapusjadwal);
        hapusjadwal.setBounds(878, 519, 286, 46);

        updatejadwal.setBackground(new java.awt.Color(204, 255, 204));
        updatejadwal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updatejadwal.setForeground(new java.awt.Color(0, 102, 51));
        updatejadwal.setText("Update Absen");
        updatejadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejadwalActionPerformed(evt);
            }
        });
        getContentPane().add(updatejadwal);
        updatejadwal.setBounds(492, 519, 286, 46);

        tambahjadwal.setBackground(new java.awt.Color(204, 255, 204));
        tambahjadwal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tambahjadwal.setForeground(new java.awt.Color(0, 102, 51));
        tambahjadwal.setText("Tambah Data");
        tambahjadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahjadwalActionPerformed(evt);
            }
        });
        getContentPane().add(tambahjadwal);
        tambahjadwal.setBounds(113, 519, 286, 46);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backround.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 1278, 703);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusjadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusjadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusjadwalActionPerformed

    private void updatejadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatejadwalActionPerformed

    private void tambahjadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahjadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahjadwalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kelolajadwalkerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kelolajadwalkerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kelolajadwalkerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kelolajadwalkerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kelolajadwalkerja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapusjadwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tambahjadwal;
    private javax.swing.JButton updatejadwal;
    // End of variables declaration//GEN-END:variables
}
