/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiadmin;

/**
 *
 * @author insan
 */
public class menuadmin extends javax.swing.JFrame {

    /**
     * Creates new form menuadmin
     */
    public menuadmin() {
        initComponents();
        this.setSize(1278, 730);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pertimbanganpengajuancuti = new javax.swing.JButton();
        kelolaabsen = new javax.swing.JButton();
        kelolajadwalkerja = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        keloladatapegawai = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pertimbanganpengajuancuti.setBackground(new java.awt.Color(204, 255, 204));
        pertimbanganpengajuancuti.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        pertimbanganpengajuancuti.setForeground(new java.awt.Color(0, 102, 51));
        pertimbanganpengajuancuti.setText("Pertimbangan Pengajuan Cuti");
        pertimbanganpengajuancuti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pertimbanganpengajuancutiActionPerformed(evt);
            }
        });
        getContentPane().add(pertimbanganpengajuancuti);
        pertimbanganpengajuancuti.setBounds(340, 540, 276, 46);

        kelolaabsen.setBackground(new java.awt.Color(204, 255, 204));
        kelolaabsen.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        kelolaabsen.setForeground(new java.awt.Color(0, 102, 51));
        kelolaabsen.setText("Kelola Absen");
        kelolaabsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelolaabsenActionPerformed(evt);
            }
        });
        getContentPane().add(kelolaabsen);
        kelolaabsen.setBounds(660, 540, 276, 46);

        kelolajadwalkerja.setBackground(new java.awt.Color(204, 255, 204));
        kelolajadwalkerja.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        kelolajadwalkerja.setForeground(new java.awt.Color(0, 102, 51));
        kelolajadwalkerja.setText("Kelola Jadwal Kerja");
        kelolajadwalkerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelolajadwalkerjaActionPerformed(evt);
            }
        });
        getContentPane().add(kelolajadwalkerja);
        kelolajadwalkerja.setBounds(970, 540, 276, 46);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelolajadwal.png"))); // NOI18N
        getContentPane().add(jLabel27);
        jLabel27.setBounds(910, 190, 370, 310);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelolaabsen.png"))); // NOI18N
        getContentPane().add(jLabel31);
        jLabel31.setBounds(590, 200, 380, 310);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pertimbangan.png"))); // NOI18N
        getContentPane().add(jLabel32);
        jLabel32.setBounds(270, 190, 410, 310);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/keloladata.png"))); // NOI18N
        getContentPane().add(jLabel33);
        jLabel33.setBounds(-30, 190, 410, 310);

        keloladatapegawai.setBackground(new java.awt.Color(204, 255, 204));
        keloladatapegawai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        keloladatapegawai.setForeground(new java.awt.Color(0, 102, 51));
        keloladatapegawai.setText("Kelola Data Pegawai");
        keloladatapegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keloladatapegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(keloladatapegawai);
        keloladatapegawai.setBounds(30, 540, 276, 46);

        jPanel6.setBackground(new java.awt.Color(51, 255, 102));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("MANAJEMENT KEPEGAWAIAN");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("RUMAH SAKIT");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel38)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 1280, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pertimbanganpengajuancutiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pertimbanganpengajuancutiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pertimbanganpengajuancutiActionPerformed

    private void kelolaabsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelolaabsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelolaabsenActionPerformed

    private void kelolajadwalkerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelolajadwalkerjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelolajadwalkerjaActionPerformed

    private void keloladatapegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keloladatapegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keloladatapegawaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton kelolaabsen;
    private javax.swing.JButton keloladatapegawai;
    private javax.swing.JButton kelolajadwalkerja;
    private javax.swing.JButton pertimbanganpengajuancuti;
    // End of variables declaration//GEN-END:variables
}
